### PR TITLE
Issue one - See All Reminders 

### LINKED ISSUE #1: See All Reminders
When the user visits the root of the application (e.g. the "/" URL), they should see a list of all of the reminders on the page.

* Each reminder should have a class of .spec-reminder-item.

* There is a failing test set up in tests/acceptance/reminder-list-test.js.

**Hot Reminder**: If you put “Closes #1” (assuming the issue is marked #1) in the pull request, your commit, or anywhere in the body of your PR, it will automatically close this issue when it successfully merged into master.

### PR DESCRIPTION
**Pull request by dylanavery720**
@martensonbj @brittanystoroz @Tman22 @adam-rice 

## Purpose

[Link to Issue](https://github.com/turingschool-projects/1610-remember-2/issues/1)

Each reminder should have a class of '.spec-reminder-item', and passes corresponding test. Closes #1   :boxing_glove: 

## Approach

We set up a path to reminders-list, and sets up the reminders list component with children components of add-reminder and reminder-item. Adds application.hbs template so that header is always rendered on screen. Set up reminders-list to iterate through reminders and display them on screen.

### Learning

We spent a good chunk of time looking over grocery-list and reviewing the ember docs. 

[https://github.com/turingschool-examples/ember-groceries](https://github.com/turingschool-examples/ember-groceries)

#### Blog Posts

[https://guides.emberjs.com/v2.6.0/templates/displaying-a-list-of-items/](https://guides.emberjs.com/v2.6.0/templates/displaying-a-list-of-items/)

### Open Questions and Pre-Merge TODOs

- [ ] Use Github checklists. When solved, check the box and explain the answer.

### Test coverage 

Tests were provided, we tried to break the test intentionally by changing the assertion from 5 to 7 and were able to confirm that it was a working test. Test passed.

### Follow-up tasks

- [Issue #2 (Example)](https://github.com/flexyford/pull-request/issues)

### Screenshots

[http://imgur.com/a/YTnte](http://imgur.com/a/YTnte)

### CODE REVIEW

File: app/components/reminders-list.js [hunk 1]
```diff
@@ -0,0 +1,4 @@
+import Ember from 'ember';
```
Comment (martensonbj) [inline app/components/reminders-list.js]: This file is unnecessary if you're not going to use it.

File: app/models/reminder.js [hunk 2]
```diff
@@ -0,0 +1,5 @@
+import DS from 'ember-data'
+
+export default DS.Model.extend({
+  text: DS.attr('string')
```
Comment (martensonbj) [inline app/models/reminder.js]: There should be more properties in the model than 'text' - what else does a reminder need to have?

File: app/router.js [hunk 3]
```diff
@@ -7,6 +7,9 @@ const Router = Ember.Router.extend({
 });
 
 Router.map(function() {
+  this.route('reminders-list', {
```
Comment (martensonbj) [inline app/router.js]: This can be on one line

File: app/routes/reminders-list.js [hunk 4]
```diff
@@ -0,0 +1,8 @@
+import Ember from 'ember';
+
+export default Ember.Route.extend({
+
```
Comment (martensonbj) [inline app/routes/reminders-list.js]: Remove extra spacing

File: app/templates/application.hbs [hunk 5]
```diff
@@ -0,0 +1,6 @@
+<div class="application">
+<header>
```
Comment (martensonbj) [inline app/templates/application.hbs]: Let's fix the indentation here - nest the child elements appropriately

File: app/templates/components/add-reminder.hbs [hunk 6]
```diff
@@ -0,0 +1,9 @@
+<h2>New Reminder</h2>
```
Comment (martensonbj) [inline app/templates/components/add-reminder.hbs]: This file has nothing to do with the current issue to "see all reminders". It makes sense that down the road we will need to add reminders, but until that feature is requested please remove extra functionality.

File: tests/integration/components/add-reminder-test.js [hunk 7]
```diff
@@ -0,0 +1,25 @@
+import { moduleForComponent, test, skip } from 'ember-qunit';
```
Comment (martensonbj) [inline tests/integration/components/add-reminder-test.js]: This is a boilerplate test. If you're going to keep this file make sure you have a legitimate assertion.

File: tests/integration/components/reminder-item-test.js [hunk 8]
```diff
@@ -0,0 +1,25 @@
+import { moduleForComponent, test, skip } from 'ember-qunit';
```
Comment (martensonbj) [inline tests/integration/components/reminder-item-test.js]: See above comment about boilerplate tests

File: tests/integration/components/reminders-list-test.js [hunk 9]
```diff
@@ -0,0 +1,25 @@
+import { moduleForComponent, test, skip } from 'ember-qunit';
```
Comment (martensonbj) [inline tests/integration/components/reminders-list-test.js]: See above comments about boilerplate tests

File: app/components/add-reminder.js [hunk 10]
```diff
@@ -0,0 +1,19 @@
...
+export default Ember.Component.extend({
+  store: Ember.inject.service(),
+
+  tagName: 'section',
+  classNames: ['add-reminder'],
+
+  text: '',
+
+  actions: {
+    createReminder() {
```
Comment (martensonbj) [inline app/components/add-reminder.js]: This issue asks simply for all reminders to be shown on '/'. Remove additional code until a later issue.

**Review by martensonbj — CHANGES_REQUESTED** [review]
Strong start - few changes requested.

**Comment by dylanavery720** [comment]
@martensonbj We have made the requested changes! Please let us know if you need anything else.

:gorilla:

File: app/models/reminder.js [hunk 11]
```diff
@@ -0,0 +1,7 @@
+import DS from 'ember-data'
+
+export default DS.Model.extend({
+  title: DS.attr('string'),
+  body: DS.attr('string'),
+  reminder_id: DS.attr('number')
```
Comment (martensonbj) [inline app/models/reminder.js]: Check out the model generated by Mirage under `factories/reminder.js`. Ember auto generates an ID for you, so the id property here is unnecessary.

File: app/components/reminders-list.js [hunk 12]
```diff
@@ -0,0 +1,2 @@
+export default Ember.Component.extend({
```
Comment (martensonbj) [inline app/components/reminders-list.js]: Are we using this component anywhere?

**Review by martensonbj — CHANGES_REQUESTED** [review]
Few last things. Thanks!

**Comment by dylanavery720** [comment]
@martensonbj ok we have made the requested changes.

File: app/models/reminder.js [hunk 13]
```diff
@@ -0,0 +1,9 @@
+import DS from 'ember-data'
+
+export default DS.Model.extend({
+  title: DS.attr('string'),
+  date: DS.attr('date'),
+  notes: DS.attr('string'),
+  pinned:
```
Comment (martensonbj) [inline app/models/reminder.js:7]: This can be on one line. This won't keep your PR from being merged in but keep an eye on formatting. Also the pinned property should have a default value of false - lets fix that for the next PR.

**Review by martensonbj — APPROVED** [review]
This won't keep your PR from being merged in but let's move

File: app/models/reminder.js (hunk 13 above)
Comment (dylanavery720) [reply app/models/reminder.js:7]: Ok @martensonbj thank you!
